// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjxohcvnh5Wvh7sA8roK12eyxV62_wwOE',
    appId: '1:819686930215:web:e0aa3c40b50615fee2db02',
    messagingSenderId: '819686930215',
    projectId: 'weather-app-4bb20',
    authDomain: 'weather-app-4bb20.firebaseapp.com',
    storageBucket: 'weather-app-4bb20.appspot.com',
    measurementId: 'G-SNE557P7ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHESM3h-0OsBIQmee3vGE_eU2-01gjnH8',
    appId: '1:819686930215:android:09c7247dbaba304ee2db02',
    messagingSenderId: '819686930215',
    projectId: 'weather-app-4bb20',
    storageBucket: 'weather-app-4bb20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU1W20MyGvinNCbwmhv73t6lMFnlsqmZA',
    appId: '1:819686930215:ios:019cf91105916479e2db02',
    messagingSenderId: '819686930215',
    projectId: 'weather-app-4bb20',
    storageBucket: 'weather-app-4bb20.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU1W20MyGvinNCbwmhv73t6lMFnlsqmZA',
    appId: '1:819686930215:ios:019cf91105916479e2db02',
    messagingSenderId: '819686930215',
    projectId: 'weather-app-4bb20',
    storageBucket: 'weather-app-4bb20.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjxohcvnh5Wvh7sA8roK12eyxV62_wwOE',
    appId: '1:819686930215:web:e8ea7fb41a3d0529e2db02',
    messagingSenderId: '819686930215',
    projectId: 'weather-app-4bb20',
    authDomain: 'weather-app-4bb20.firebaseapp.com',
    storageBucket: 'weather-app-4bb20.appspot.com',
    measurementId: 'G-GY7DPTF54R',
  );
}
